# Generated by Django 6.0.4 on 2026-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expense_description_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
